<?php

namespace IntranetBundle\Repository;

/**
 * matterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matterRepository extends \Doctrine\ORM\EntityRepository
{
}
